### ISSUE TITLE
[Help] Package Resolution Failed

### ISSUE THREAD

**Issue by allenleein** [michaelnisi/feedkit#29]
'https://github.com/michaelnisi/feedkit.git has no Package.swift manifest'

![363BFF5D-8132-48A8-8243-85A3684989E2](https://user-images.githubusercontent.com/3938314/78106610-53b26180-7426-11ea-8933-367363168f38.png)

**Comment by michaelnisi** [comment]
Sorry, not a Swift Package yet. But of course, I’m planning to switch Podest over to using Packages soon. Thanks for your interest.
